### ISSUE TITLE
Unable to load addon, no "Detected map" string

### ISSUE THREAD

**Issue by TeamPopplio** [TeamPopplio/KCOM#2]
Under different user configurations, players cannot load the addon when launching the software and loading a map.

This could be due to issue #1 but other factors can contribute as well.

If you are having this problem, please let me know what your configuration is using the template below:

> Hosting a dedicated server? Yes/No
> Connecting to a remote server? Yes/No
> Self-hosting/hosting a listen server? Yes/No
> Player count? 1-16
> Can players connect? Yes/No
> Does "Detected map" show up in the output? Yes/No
> Do all players have the KCOM addon enabled? Yes/No
> What is your launch options? [Paste from Steam]
> Is your game's language set to English? Yes/No
> Have you already tried troubleshooting steps? Yes/No

Thank you for helping with solving this issue!

**Comment by niko20010** [comment]
Hosting a dedicated server? No
Connecting to a remote server? No
Self-hosting/hosting a listen server? Yes
Player count? 2
Can players connect? Yes
Does "Detected map" show up in the output? Yes
Do all players have the KCOM addon enabled? Yes
What is your launch options? -console -vconsole -dev 
Is your game's language set to English? Yes
Have you already tried troubleshooting steps? Yes


after map load nothing is synchronised and second player doesnt show up at all

**Comment by TeamPopplio** [comment]
I believe this is fixed in #5 as part of v3.0.0.0.
